apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: group-pvc
  labels:
    vol: nginx
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      vol: nginx
