apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: group
spec:
  serviceName: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nginx
        image: onyiokoligwe/project:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-vol
        persistentVolumeClaim:
          claimName: group-pvc
